// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// R_interface.cpp
void R_sync_rng();
extern "C" SEXP _seine_R_sync_rng() {
  BEGIN_CPP11
    R_sync_rng();
    return R_NilValue;
  END_CPP11
}
// R_interface.cpp
doubles_matrix<> R_ess_tmvn(int N, const doubles& mu, const doubles_matrix<>& L, const doubles& init);
extern "C" SEXP _seine_R_ess_tmvn(SEXP N, SEXP mu, SEXP L, SEXP init) {
  BEGIN_CPP11
    return cpp11::as_sexp(R_ess_tmvn(cpp11::as_cpp<cpp11::decay_t<int>>(N), cpp11::as_cpp<cpp11::decay_t<const doubles&>>(mu), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(L), cpp11::as_cpp<cpp11::decay_t<const doubles&>>(init)));
  END_CPP11
}
// R_interface.cpp
list R_ep_moments(const doubles& mu, const doubles_matrix<>& L, const doubles& addl_c, double addl_shift, double tol);
extern "C" SEXP _seine_R_ep_moments(SEXP mu, SEXP L, SEXP addl_c, SEXP addl_shift, SEXP tol) {
  BEGIN_CPP11
    return cpp11::as_sexp(R_ep_moments(cpp11::as_cpp<cpp11::decay_t<const doubles&>>(mu), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(L), cpp11::as_cpp<cpp11::decay_t<const doubles&>>(addl_c), cpp11::as_cpp<cpp11::decay_t<double>>(addl_shift), cpp11::as_cpp<cpp11::decay_t<double>>(tol)));
  END_CPP11
}
// R_interface.cpp
list R_bounds_lp(const doubles_matrix<>& x, const doubles_matrix<>& y, const doubles& bounds);
extern "C" SEXP _seine_R_bounds_lp(SEXP x, SEXP y, SEXP bounds) {
  BEGIN_CPP11
    return cpp11::as_sexp(R_bounds_lp(cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(x), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(y), cpp11::as_cpp<cpp11::decay_t<const doubles&>>(bounds)));
  END_CPP11
}

extern "C" {
/* .Call calls */
extern SEXP run_testthat_tests(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_seine_R_bounds_lp",  (DL_FUNC) &_seine_R_bounds_lp,  3},
    {"_seine_R_ep_moments", (DL_FUNC) &_seine_R_ep_moments, 5},
    {"_seine_R_ess_tmvn",   (DL_FUNC) &_seine_R_ess_tmvn,   4},
    {"_seine_R_sync_rng",   (DL_FUNC) &_seine_R_sync_rng,   0},
    {"run_testthat_tests",  (DL_FUNC) &run_testthat_tests,  1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_seine(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
