# Generated by cpp11: do not edit by hand

R_sync_rng <- function() {
  invisible(.Call(`_seine_R_sync_rng`))
}

R_ess_tmvn <- function(N, mu, L, init) {
  .Call(`_seine_R_ess_tmvn`, N, mu, L, init)
}

R_ep_moments <- function(mu, L, addl_c, addl_shift, tol) {
  .Call(`_seine_R_ep_moments`, mu, L, addl_c, addl_shift, tol)
}

R_utn_moments <- function(mu, sigma2) {
  .Call(`_seine_R_utn_moments`, mu, sigma2)
}

R_llik <- function(eta, L, y, X, weights, p, tol) {
  .Call(`_seine_R_llik`, eta, L, y, X, weights, p, tol)
}

R_draw_local <- function(draws, eta, L, y, X, warmup, tol) {
  .Call(`_seine_R_draw_local`, draws, eta, L, y, X, warmup, tol)
}

r_proj_mvn <- function(eta, l, x, eps) {
  .Call(`_seine_r_proj_mvn`, eta, l, x, eps)
}
