# Generated by cpp11: do not edit by hand

R_sync_rng <- function() {
  invisible(.Call(`_seine_R_sync_rng`))
}

R_ess_tmvn <- function(N, mu, L, init) {
  .Call(`_seine_R_ess_tmvn`, N, mu, L, init)
}

R_ep_moments <- function(mu, L, addl_c, addl_shift, tol) {
  .Call(`_seine_R_ep_moments`, mu, L, addl_c, addl_shift, tol)
}

R_bounds_lp <- function(x, y, bounds) {
  .Call(`_seine_R_bounds_lp`, x, y, bounds)
}

R_bounds_lp_contrast <- function(x, y, contr_m, ub, scale, shift, sum_one, has_ub) {
  .Call(`_seine_R_bounds_lp_contrast`, x, y, contr_m, ub, scale, shift, sum_one, has_ub)
}
